name: CMake on a single platform

on:
  push:
    branches: [ "assignment6" ]
  pull_request:
    branches: [ "assignment6" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Install Qt 6.9.2
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.2'
        host: windows
        target: desktop
        arch: win64_msvc2022_64

    # Configure CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Build the project
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    # Run Qt tests manually in offscreen mode
    - name: Run Qt Tests
      working-directory: build
      run: |
        set QT_QPA_PLATFORM_PLUGIN_PATH=%QT_ROOT_DIR%/plugins/platforms

        # Run each Qt test executable
        .\bin\tst_homepage.exe -platform offscreen -v2
        .\bin\tst_databasequiz.exe -platform offscreen -v2
        .\bin\tst_flashcardstudy.exe -platform offscreen -v2
        .\bin\tst_flashcardmaker.exe -platform offscreen -v2
        .\bin\quizwindowUnitTests.exe -platform offscreen -v2
